#!/usr/bin/env bash

# I3gaps e pacotes essências:
sudo pacman -S kitty gimp thunar ffmpegthumbnailer tumbler ranger

# Brilho de tela
pacman -Qi brightnessctl
sudo pacman -S brightnessctl
bindsym XF86MonBrightnessUp exec brightnessctl -c backlight set +1% 
bindsym XF86MonBrightnessDown exec brightnessctl -c backlight set 1%-

# Editor de texto via CLI:
sudo pacman -S vim
sudo pacman -R nano

# Gerenciador de diretórios:
sudo pacman -S xdg-user-dirs
# Atualizando gerenciador de diretórios:
xdg-user-dirs-update

# Editor de texto gráfico:
sudo pacman -S

# Ferramenta para setar o wallpaper:
sudo pacman -S feh 
# Tornando wallpaper permanente:
feh --bg-fill /usr/share/backgrounds/archlinux/car01.jpg
sudo vim ~/.config/i3/config
# Adicione essa linha no arquivo:
exec_always feh --bg-fill /usr/share/backgrounds/archlinux/car01.jpg

# Transparência no terminal:
sudo pacman -S picom
# Tornando transparência permanente:
sudo vim ~/.config/i3/config
# Adicione essa linha no arquivo:
exec_always picom -f

# Instalando temas:
sudo pacman -S arc-gtk-theme arc-icon-theme
# Ferramente para lidar com temas:
sudo pacman -S lxappearance

# Reprodutor de áudio e vídeo:
sudo pacman -S mplayer

# Tela de bloqueio
cd /home/fabio/.config/i3blocks/scripts
wget https://raw.githubusercontent.com/Raymo111/i3lock-color/master/examples/lock.sh
chmod +x lock.sh
# Colocar no arquivo de configuraçao do i3
bindsym $mod+x exec /home/fabio/.config/i3blocks/scripts/lock.sh

# Personalização final:
sudo pacman -S neofetch cmatrix lolcat

